package practicabancaria;


import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Carlos
 */
public class ViewClientes extends javax.swing.JFrame {
    private ArrayList<Cliente> arrayClientes;
    /**
     * Creates new form ViewClientes
     */
    public ViewClientes() {
        initComponents();
    }
    
    public ViewClientes(ArrayList<Cliente> clientes) {
        this.arrayClientes=clientes;
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnUpdateClientes = new javax.swing.JButton();
        btnDeletePublicacion = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DNI", "Comunicacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        btnUpdateClientes.setText("Modificar");
        btnUpdateClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateClientesMouseClicked(evt);
            }
        });

        btnDeletePublicacion.setText("Eliminar");
        btnDeletePublicacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeletePublicacionMouseClicked(evt);
            }
        });

        btnExit.setText("Salir");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btnUpdateClientes)
                .addGap(108, 108, 108)
                .addComponent(btnDeletePublicacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit)
                    .addComponent(btnUpdateClientes)
                    .addComponent(btnDeletePublicacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateClientesMouseClicked
        int position = tblClientes.getSelectedRow();
        if (position!=-1) {
            DefaultTableModel dtm = (DefaultTableModel)tblClientes.getModel();
            FormCliente form = new FormCliente(arrayClientes,position);
            form.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnUpdateClientesMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnDeletePublicacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletePublicacionMouseClicked
        // TODO add your handling code here:                                            
        DefaultTableModel dtm = (DefaultTableModel)tblClientes.getModel();
        int position = tblClientes.getSelectedRow();
        if (position!=-1) {
            String DNI = (String)dtm.getValueAt(position, 1);
            this.arrayClientes.remove(BuscaPerfil(DNI));
            dtm.removeRow(position);
        }
        

    }//GEN-LAST:event_btnDeletePublicacionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewClientes().setVisible(true);
            }
        });
    }
    
     private void loadData() {
        
        DefaultTableModel tm = (DefaultTableModel)tblClientes.getModel();
        
        Iterator<Cliente> it = this.arrayClientes.iterator();
        while (it.hasNext()) {
            Cliente p = it.next();
            Object[] rowData = new Object[5];
            rowData[0] = p.getNombre();
            rowData[1] = p.getDni();
            rowData[2] = p.getComunicacion();
            tm.addRow(rowData);
        }
    }
     
     
    public Cliente BuscaPerfil(String DNI) {
    Cliente resultado = null;
    for (Cliente cliente : this.arrayClientes) {
        if (cliente.getDni().equals(DNI)) {
            resultado = cliente;
            break;
        }
    }
    return resultado;
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeletePublicacion;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnUpdateClientes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
